language: rust
rust:
  - stable
  - nightly
install:
  - rustup component add clippy
  - rustup component add rustfmt
matrix:
  allow_failures:
  - rust: nightly
script:
  - cargo fmt -- --check
  - touch ./src/bin/main.rs && touch ./src/lib.rs && touch ./src/create_cred_config/mod.rs && touch ./src/read_csv/mod.rs && touch ./src/write_config/mod.rs && cargo clippy -- -D warnings
  - cargo check
  - cargo build --verbose --all

